matrix:
    include:
        - language: python
          python:
              - "3.6"
          script:
              - pytest

        - language: node_js
          node_js:
              - "node"
          before_script:
              - cd imageserver
              - npm i
          script:
              - npm test
